name: Github Actions example
on: [push]
jobs:
  Explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Event trigger info
        run: echo "This job will automatically triggered by ${{ github.event_name }} event"
      - name: Runner info
        run: echo "This job is now running on a ${{ runner.os }} machine!"
      - name: branch and repo info
        run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository}}."
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Repository clone confirmation
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Workflow ready message
        run: echo "Your workflow is now ready to test your code on the runner."
      - name: store and retrieve secrets in workflow file
        env:
          MY_SECRET: ${{ secrets.SECRET_VALUE }}
        run: echo "Secret value is $MY_SECRET" # this will expose the secret
#      - name: Connect to aws account
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-south-1
      - name: Connect to AWS account
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-south-1
      - name: check the aws connection
        run: aws s3 ls
